import type { Home } from '@/payload-types'

/**
 * English fallbacks when CMS / locale data is missing. CMS always wins when present.
 */
export const HOME_DEFAULTS: Partial<Home> = {
  siteName: 'CoffeeLab',
  skipLinkLabel: 'Skip to main content',
  accountAriaLabel: 'Account',
  cartAriaLabel: 'Cart',
  heroKicker: 'LAB PROTOCOL // ACTIVE',
  heroTitleLine1: 'MOLECULAR',
  heroTitleLine2: 'ROASTERY',
  heroSubtitle:
    'Explore the biological frontier of Espresso and Filter extraction via digital synthesis.',
  heroAccentWord1: '',
  heroAccentWord2: '',
  heroPrimaryCtaLabel: 'INITIALIZE_SYSTEM',
  heroPrimaryCtaHref: '#roastery',
  heroSecondaryCtaLabel: 'SECURE_ARCHIVES',
  heroSecondaryCtaHref: '#archives',
  navItems: [
    { label: 'SHOP', href: '#roastery' },
    { label: 'VARIABLE LAB', href: '#variable-lab' },
    { label: 'GENETIC BLENDING', href: '#genetic-blending' },
    { label: 'THE VAULT', href: '#vault' },
    { label: 'WHITEPAPERS', href: '#whitepapers' },
  ],
  laboratoryPhase: 'LABORATORY STORE',
  laboratoryTitle: 'Featured Specimens',
  laboratoryIntro:
    'Curated selection of single-origin coffees and precision-engineered blends. All specimens roasted to order in our molecular laboratory.',
  laboratoryEmptyFilter: 'No specimens match this filter.',
  laboratoryPriceLabel: 'PRICE / 12OZ',
  laboratoryAddToCartAriaTemplate: 'Add {title} to cart',
  storeFilters: [
    { id: 'all', label: 'ALL' },
    { id: 'bestseller', label: 'BESTSELLER' },
    { id: 'single-origin', label: 'SINGLE ORIGIN' },
    { id: 'espresso-blend', label: 'ESPRESSO BLEND' },
    { id: 'rare-varietal', label: 'RARE VARIETAL' },
  ],
  labStats: [
    { value: '50+', label: 'PRODUCTS', icon: 'box' },
    { value: '92.5', label: 'QUALITY SCORE', icon: 'medal' },
    { value: '4.8', label: 'AVG RATING', icon: 'star' },
    { value: '5,200+', label: 'HAPPY CUSTOMERS', icon: 'trend' },
  ],
  protocolEyebrow: 'EXTRACTION PROTOCOL',
  protocolTitle: 'System Calibration',
  brewEspressoLabel: 'ESPRESSO',
  brewFilterLabel: 'FILTER',
  geneticSection: {
    mediaTag: '32% PROFIT RE-INJECTION',
    phase: 'PHASE_01',
    title: 'Direct Genetic Sourcing',
    body:
      'We analyze the DNA of every micro-lot. Our direct relationships ensure farmers receive 3x the standard market rate, securing the future of high-altitude specialty beans.',
    ctaLabel: 'INITIALIZE_ARCHIVE',
    ctaHref: '#archives',
  },
  thermalSection: {
    mediaTag: '0.05°C VARIANCE LIMIT',
    phase: 'PHASE_02',
    title: 'Thermal Roasting Precision',
    body:
      'Our Loring smart-roasters capture 1,200 data points per second. We hit the exact chemical transition point where acidity transforms into complex sweetness.',
    ctaLabel: 'INITIALIZE_ARCHIVE',
    ctaHref: '#archives',
  },
  valueSection: {
    mediaTag: '100% COST TRANSPARENCY',
    phase: 'PHASE_03',
    title: 'Transparent Value Index',
    body:
      'No marketing fluff. We open-source our costs. You see the bean price, the logistics, and the roasting energy. Fair pricing, scientifically calculated.',
    ctaLabel: 'INITIALIZE_ARCHIVE',
    ctaHref: '#archives',
  },
  precisionPhase: 'PRECISION LAB',
  precisionTitle: 'Molecular Customization',
  precisionIntro:
    'Tinker with the chemical variables. As an expert, you control the extraction curves for the filter profile.',
  precisionPanelTitle: 'EXTRACTION LAB',
  precisionStatusPrefix: 'STATUS: ACTIVE //',
  axisRoast: 'ROAST',
  axisAcidity: 'ACIDITY',
  axisBody: 'BODY',
  axisSweetness: 'SWEETNESS',
  axisComplexity: 'COMPLEXITY',
  matrixHeading: 'EXTRACTION MATRIX:',
  matrixTagsEspresso: [
    { text: 'MAILLARD RICHNESS' },
    { text: 'CARAMELIZED FINISH' },
    { text: 'HIGH VISCOSITY' },
  ],
  matrixTagsFilter: [
    { text: 'CITRIC BRIGHTNESS' },
    { text: 'CARAMELIZED FINISH' },
    { text: 'VOLATILE FLAVORS' },
  ],
  synthesizeButton: 'SYNTHESIZE FLAVOR PROFILE',
  scanStats: [
    { template: 'SCAN_UID: X-992' },
    { template: 'BEAM_TEMP: {beam}°C' },
    { template: 'WATER_V: {water}%' },
  ],
  roastSliderLabel: 'Set Roast Target',
  radarAriaLabel: 'Live flavor radar chart',
  flavorNote: 'Flavor profile updates in real-time as roast level changes.',
  blendingPhase: 'GENETIC FUSION',
  blendingTitle: 'The Blending Chamber',
  blendingIntro: 'Synthesis of rare micro-lots optimized for clarity of terroir.',
  blendingTabExpert: 'EXPERT CURATION',
  blendingTabManual: 'MANUAL ASSEMBLY',
  blendingExpertCards: [
    {
      intensityLabel: 'ETHEREAL INTENSITY',
      title: 'Prism Clarity',
      sensoryFilter: '"Tea-like body, jasmine florals, white peach acidity."',
      sensoryEspresso: '"Dense crema, chocolate backbone, concentrated sweetness."',
      geneticBase: 'Ethiopia Yirgacheffe (Washed)',
      methodologyFilter: 'FILTER EXTRACTION',
      methodologyEspresso: 'ESPRESSO EXTRACTION',
      price: '$28.00',
      cta: 'INITIALIZE_TRANSMISSION',
    },
    {
      intensityLabel: 'VIBRANT INTENSITY',
      title: 'Neon Horizon',
      sensoryFilter: '"Vibrant berry notes, sparkling acidity, honey finish."',
      sensoryEspresso: '"Heavy body, caramelized sugars, long syrupy finish."',
      geneticBase: 'Kenya Nyeri + Colombia Pink Bourbon',
      methodologyFilter: 'FILTER EXTRACTION',
      methodologyEspresso: 'ESPRESSO EXTRACTION',
      price: '$25.00',
      cta: 'INITIALIZE_TRANSMISSION',
    },
  ],
  manualAssemblerTitle: 'GENETIC ASSEMBLER',
  manualAssemblerProtocolPrefix: 'PROTOCOL: MANUAL_OVERRIDE //',
  manualRecalibrate: 'RECALIBRATE',
  manualRowsEspresso: [
    { code: 'MOGIANA // SPECIMEN', name: 'Brazilian Santos' },
    { code: 'MALABAR // SPECIMEN', name: 'Indian Monsooned' },
    { code: 'LAB SELECT // SPECIMEN', name: 'Dark Roast Blend' },
  ],
  manualRowsFilter: [
    { code: 'GUJI // SPECIMEN', name: 'Ethiopian Heirloom' },
    { code: 'GEISHA // SPECIMEN', name: 'Panama Geisha' },
    { code: 'LAB SELECT // SPECIMEN', name: 'Light Roast Blend' },
  ],
  saturationLabel: 'SATURATION',
  stabilityLabel: 'STABILITY_CHECK',
  stabilityLocked: 'SYSTEM_LOCKED',
  stabilityCalibrating: 'CALIBRATING...',
  finalizeAssembly: 'FINALIZE ASSEMBLY',
  vaultPhase: 'SENSORY DECOUPLING',
  vaultTitle: 'Classified Vault',
  vaultIntro:
    'Zero branding. Zero expectations. Just the pure biological response to the roast.',
  vaultCuppingLabel: 'CUPPING SCORE',
  vaultSpecimenYear: 'SPECIMEN // 2026',
  vaultMetadataLabel: 'METADATA:',
  vaultMetadataValue: 'ENCRYPTED_FOR_RESEARCHERS',
  vaultCards: [
    {
      score: '91.5',
      title: 'PROTOCOL X-771',
      label: 'EXPERIMENTAL PROFILE',
      description:
        'A profile that challenges the biological limits of perception. High thermal variability during roast.',
      priceButton: 'SECURE_SAMPLE // $32.00',
    },
    {
      score: '89.0',
      title: 'PROTOCOL X-442',
      label: 'ANAEROBIC MICROLOT',
      description:
        'Sourced from a secret high-altitude plot. Identity hidden to prevent expectation bias.',
      priceButton: 'SECURE_SAMPLE // $32.00',
    },
    {
      score: '92.2',
      title: 'PROTOCOL X-901',
      label: 'CARBONIC MACERATION',
      description: 'The pinnacle of our laboratory efforts. Pure molecular expression of terroir.',
      priceButton: 'SECURE_SAMPLE // $32.00',
    },
  ],
  footerTagline: 'MOLECULAR ROASTERY // STATION_772',
  footerMission:
    'A decentralized collective of roasters and data scientists. Redefining extraction through radical transparency and digital precision.',
  footerMapTitle: 'SYSTEM_MAP',
  footerMapLinks: [
    { label: 'VARIABLE LAB', href: '#variable-lab' },
    { label: 'GENETIC BLENDING', href: '#genetic-blending' },
    { label: 'THE VAULT', href: '#vault' },
    { label: 'WHITEPAPERS', href: '#whitepapers' },
  ],
  footerOpsTitle: 'OPERATIONS',
  footerOpsLinks: [
    { label: 'LOGISTICS', href: '#logistics' },
    { label: 'EXCHANGES', href: '#exchange' },
    { label: 'COLLECTIVE', href: '#collective' },
    { label: 'TERMINAL', href: '#terminal' },
  ],
  footerFeedTitle: 'NEURAL_FEED',
  footerFeedDescription: 'Receive extraction logs & sensory data streams',
  footerFeedPlaceholder: 'sample@mail.com',
  footerFeedSubmit: 'SECURE',
  footerFeedEncryption: 'ENCRYPTION ACTIVE',
  footerFeedSuccess: 'Opening your email app — send the message to subscribe.',
  footerCopyright: '© {year} CoffeeLab. All rights reserved.',
  neuralFeedMailSubject: 'CoffeeLab // Neural feed subscription',
  neuralFeedMailBodyIntro:
    'Please notify me about extraction logs and sensory data streams.',
}
