import type { Home } from '@/payload-types'

/**
 * German (de) seed strings for the `home` global — CoffeeLab molecular roastery.
 */
export const HOME_SEED_DE: Partial<Home> = {
  siteName: 'CoffeeLab',
  skipLinkLabel: 'Zum Hauptinhalt springen',
  accountAriaLabel: 'Konto',
  cartAriaLabel: 'Warenkorb',
  heroKicker: 'LABOR-PROTOKOLL // AKTIV',
  heroTitleLine1: 'MOLEKULAR',
  heroTitleLine2: 'RÖSTEREI',
  heroSubtitle:
    'Erkunde die biologische Grenze von Espresso- und Filter-Extraktion — digital synthetisiert.',
  heroAccentWord1: '',
  heroAccentWord2: '',
  heroPrimaryCtaLabel: 'SYSTEM_INITIALISIEREN',
  heroPrimaryCtaHref: '#roastery',
  heroSecondaryCtaLabel: 'ARCHIVE_SICHERN',
  heroSecondaryCtaHref: '#archives',
  navItems: [
    { label: 'SHOP', href: '#roastery' },
    { label: 'VARIABLE LAB', href: '#variable-lab' },
    { label: 'GENETIC BLENDING', href: '#genetic-blending' },
    { label: 'THE VAULT', href: '#vault' },
    { label: 'WHITEPAPERS', href: '#whitepapers' },
  ],
  laboratoryPhase: 'LABOR-LADEN',
  laboratoryTitle: 'Ausgewählte Proben',
  laboratoryIntro:
    'Kuratierte Single Origins und präzisionsgeröstete Blends. Alle Proben auf Bestellung in unserem molekularen Labor geröstet.',
  laboratoryEmptyFilter: 'Keine Proben passen zu diesem Filter.',
  laboratoryPriceLabel: 'PREIS / 12OZ',
  laboratoryAddToCartAriaTemplate: '{title} in den Warenkorb legen',
  storeFilters: [
    { id: 'all', label: 'ALLE' },
    { id: 'bestseller', label: 'BESTSELLER' },
    { id: 'single-origin', label: 'SINGLE ORIGIN' },
    { id: 'espresso-blend', label: 'ESPRESSO BLEND' },
    { id: 'rare-varietal', label: 'SELTENE VARIETÄT' },
  ],
  protocolEyebrow: 'EXTRACTIONSPROTOKOLL',
  protocolTitle: 'Systemkalibrierung',
  brewEspressoLabel: 'ESPRESSO',
  brewFilterLabel: 'FILTER',
  geneticSection: {
    mediaTag: '32% GEWINN-RÜCKFÜHRUNG',
    phase: 'PHASE_01',
    title: 'Direkte genetische Beschaffung',
    body:
      'Wir analysieren die DNA jeder Mikrolot-Partie. Unsere Direktbeziehungen stellen sicher, dass Produzent:innen das Dreifache des Marktpreises erhalten.',
    ctaLabel: 'ARCHIV_INITIALISIEREN',
    ctaHref: '#archives',
  },
  thermalSection: {
    mediaTag: '0,05°C VARIANZGRENZE',
    phase: 'PHASE_02',
    title: 'Thermische Röst-Präzision',
    body:
      'Unsere Smart-Röster erfassen 1.200 Datenpunkte pro Sekunde — genau am chemischen Übergang, an dem Säure in komplexe Süße übergeht.',
    ctaLabel: 'ARCHIV_INITIALISIEREN',
    ctaHref: '#archives',
  },
  valueSection: {
    mediaTag: '100% KOSTENTRANSPARENZ',
    phase: 'PHASE_03',
    title: 'Transparenter Werte-Index',
    body:
      'Kein Marketing-Blabla. Wir legen Kosten offen: Rohkaffee, Logistik, Röstenergie — fair kalkuliert.',
    ctaLabel: 'ARCHIV_INITIALISIEREN',
    ctaHref: '#archives',
  },
  precisionPhase: 'PRECISION LAB',
  precisionTitle: 'Molekulare Anpassung',
  precisionIntro:
    'Justiere die chemischen Variablen. Als Expert:in steuerst du die Extraktionskurven für das Filterprofil.',
  precisionPanelTitle: 'EXTRACTION LAB',
  precisionStatusPrefix: 'STATUS: AKTIV //',
  axisRoast: 'RÖSTUNG',
  axisAcidity: 'SÄURE',
  axisBody: 'KÖRPER',
  axisSweetness: 'SÜSSE',
  axisComplexity: 'KOMPLEXITÄT',
  matrixHeading: 'EXTRACTION MATRIX:',
  matrixTagsEspresso: [
    { text: 'MAILLARD-FÜLLE' },
    { text: 'KARAMELLISIERTER ABKLANG' },
    { text: 'HOHE VISKOSITÄT' },
  ],
  matrixTagsFilter: [
    { text: 'ZITRISCHE HELLE NOTEN' },
    { text: 'KARAMELLISIERTER ABKLANG' },
    { text: 'FLÜCHTIGE AROMEN' },
  ],
  synthesizeButton: 'GESCHMACKSPROFIL SYNTHETISIEREN',
  scanStats: [
    { template: 'SCAN_UID: X-992' },
    { template: 'BEAM_TEMP: {beam}°C' },
    { template: 'WATER_V: {water}%' },
  ],
  roastSliderLabel: 'Röstziel setzen',
  radarAriaLabel: 'Live-Flavor-Radar',
  flavorNote: 'Das Geschmacksprofil aktualisiert sich in Echtzeit mit der Röstung.',
  blendingPhase: 'GENETIC FUSION',
  blendingTitle: 'Die Blending-Kammer',
  blendingIntro: 'Synthese seltener Mikrolots — optimiert für Klarheit des Terroirs.',
  blendingTabExpert: 'EXPERTEN-KURATION',
  blendingTabManual: 'MANUELLE MONTAGE',
  blendingExpertCards: [
    {
      intensityLabel: 'ÄTHERISCHE INTENSITÄT',
      title: 'Prism Clarity',
      sensoryFilter: '"Teeartiger Körper, Jasmin, weiße Pfirsichsäure."',
      sensoryEspresso: '"Dichte Crema, Schokolade, konzentrierte Süße."',
      geneticBase: 'Äthiopien Yirgacheffe (gewaschen)',
      methodologyFilter: 'FILTER-EXTRACTION',
      methodologyEspresso: 'ESPRESSO-EXTRACTION',
      price: '$28.00',
      cta: 'ÜBERTRAGUNG_STARTEN',
    },
    {
      intensityLabel: 'VIBRANTE INTENSITÄT',
      title: 'Neon Horizon',
      sensoryFilter: '"Beeren, spritzige Säure, Honigabgang."',
      sensoryEspresso: '"Schwerer Körper, karamellisierte Süße, sirupartiger Abgang."',
      geneticBase: 'Kenia Nyeri + Kolumbien Pink Bourbon',
      methodologyFilter: 'FILTER-EXTRACTION',
      methodologyEspresso: 'ESPRESSO-EXTRACTION',
      price: '$25.00',
      cta: 'ÜBERTRAGUNG_STARTEN',
    },
  ],
  manualAssemblerTitle: 'GENETISCHER ASSEMBLER',
  manualAssemblerProtocolPrefix: 'PROTOKOLL: MANUELL //',
  manualRecalibrate: 'NEU KALIBRIEREN',
  manualRowsEspresso: [
    { code: 'MOGIANA // PROBE', name: 'Brasilien Santos' },
    { code: 'MALABAR // PROBE', name: 'Indien Monsooned' },
    { code: 'LAB SELECT // PROBE', name: 'Dark Roast Blend' },
  ],
  manualRowsFilter: [
    { code: 'GUJI // PROBE', name: 'Äthiopien Heirloom' },
    { code: 'GEISHA // PROBE', name: 'Panama Geisha' },
    { code: 'LAB SELECT // PROBE', name: 'Light Roast Blend' },
  ],
  saturationLabel: 'SÄTTIGUNG',
  stabilityLabel: 'STABILITÄTSPRÜFUNG',
  stabilityLocked: 'SYSTEM_GESPERRT',
  stabilityCalibrating: 'KALIBRIERUNG...',
  finalizeAssembly: 'MONTAGE ABSCHLIESSEN',
  vaultPhase: 'SENSORISCHE ENTKOPPLUNG',
  vaultTitle: 'Klassifiziertes Archiv',
  vaultIntro:
    'Kein Branding. Keine Erwartung. Nur die biologische Reaktion auf die Röstung.',
  vaultCuppingLabel: 'CUPPING-SCORE',
  vaultSpecimenYear: 'PROBE // 2026',
  vaultMetadataLabel: 'METADATEN:',
  vaultMetadataValue: 'VERSCHLÜSSELT_FÜR_FORSCHUNG',
  vaultCards: [
    {
      score: '91.5',
      title: 'PROTOKOLL X-771',
      label: 'EXPERIMENTELLES PROFIL',
      description:
        'Ein Profil an der Grenze der Wahrnehmung. Hohe thermische Variabilität während der Röstung.',
      priceButton: 'PROBE_SICHERN // $32.00',
    },
    {
      score: '89.0',
      title: 'PROTOKOLL X-442',
      label: 'ANAEROBES MIKROLOT',
      description:
        'Geheim gelegene Hochland-Parzelle. Identität verborgen gegen Erwartungsbias.',
      priceButton: 'PROBE_SICHERN // $32.00',
    },
    {
      score: '92.2',
      title: 'PROTOKOLL X-901',
      label: 'CARBONIC MACERATION',
      description: 'Höhepunkt unserer Laborarbeiten. Reine molekulare Terroir-Expression.',
      priceButton: 'PROBE_SICHERN // $32.00',
    },
  ],
  footerTagline: 'MOLEKULAR-RÖSTEREI // STATION_772',
  footerMission:
    'Ein dezentrales Kollektiv aus Röster:innen und Datenwissenschaftler:innen. Extraktion neu definiert — radikal transparent, digital präzise.',
  footerMapTitle: 'SYSTEM_MAP',
  footerMapLinks: [
    { label: 'VARIABLE LAB', href: '#variable-lab' },
    { label: 'GENETIC BLENDING', href: '#genetic-blending' },
    { label: 'THE VAULT', href: '#vault' },
    { label: 'WHITEPAPERS', href: '#whitepapers' },
  ],
  footerOpsTitle: 'OPERATIONS',
  footerOpsLinks: [
    { label: 'LOGISTICS', href: '#logistics' },
    { label: 'EXCHANGES', href: '#exchange' },
    { label: 'COLLECTIVE', href: '#collective' },
    { label: 'TERMINAL', href: '#terminal' },
  ],
  footerFeedTitle: 'NEURAL_FEED',
  footerFeedDescription: 'Extraktions-Logs & sensorische Datenströme erhalten',
  footerFeedPlaceholder: 'sample@mail.com',
  footerFeedSubmit: 'SICHERN',
  footerFeedEncryption: 'VERSCHLÜSSELUNG AKTIV',
  footerFeedSuccess: 'E-Mail-App öffnet — Nachricht senden zum Abonnieren.',
  footerCopyright: '© {year} CoffeeLab. Alle Rechte vorbehalten.',
  neuralFeedMailSubject: 'CoffeeLab // Neural Feed',
  neuralFeedMailBodyIntro:
    'Bitte über Extraktions-Logs und sensorische Datenströme informieren.',
  labStats: [
    { value: '50+', label: 'PRODUKTE', icon: 'box' },
    { value: '92.5', label: 'QUALITÄTSSCORE', icon: 'medal' },
    { value: '4.8', label: 'Ø BEWERTUNG', icon: 'star' },
    { value: '5.200+', label: 'ZUFRIEDENE KUND:INNEN', icon: 'trend' },
  ],
}
